### ISSUE TITLE
unable to run this project

### ISSUE THREAD

**Issue by mimrank** [moeen-basra/laravel-react#4]
Hi, i try to run it but its not work.
![image](https://user-images.githubusercontent.com/10322671/32607295-4de5ebee-c57a-11e7-822e-3066bbcebe61.png)

![image](https://user-images.githubusercontent.com/10322671/32607368-928d71e0-c57a-11e7-842f-99b197d8753a.png)

![image](https://user-images.githubusercontent.com/10322671/32607480-040fa3ec-c57b-11e7-868b-21b78153ffb7.png)

**Comment by SagarNaliyapara** [comment]
I have same issue @mimrank add following into `resources/assets/js/store/config.js`,

```
  const store = createStore(
      rootReducer,
      initialState,
      compose(applyMiddleware(thunk))
  );
```
and remove this line which will be replaced by above,
```
  const store = createStore(rootReducer, initialState, compose(...enhancers))
```

@moeen-basra please change this

**Comment by moeen-basra** [comment]
Sorry for inconvenience, this issue occured as I removed the extension 
`redux-devtools-dock-monitor`
due to compatibility issue with react 16 and mistakenly added window's extention check within the `enhancers.push()`.

The following line was caused the issue

`enhancers.push(window.devToolsExtension && window.devToolsExtension())`

and is fixed and replaced by the following code

`window.devToolsExtension && enhancers.push(window.devToolsExtension())`

**Comment by mimrank** [comment]
now login and registration not work

**Comment by rummykhan** [comment]
hey @mimrank are you sure it's not working, did you followed all the steps in readme?
